 

// ******************************************************
// DO NOT CHANGE THE CONTENT OF THIS FILE
// This file was generated by the T4 engine and the 
// contents of this source code will be changed after
// the custom tool was run.
// ******************************************************
using System;
using System.Collections.Generic;
using System.ServiceModel;
using CSMS3.Application;
using CSMS3.Application.DTO;
using CSMS3.ApplicationContract;
using CSMS3.Infrastructure;

namespace CSMS3.ApplicationService
{
	[ServiceBehavior(InstanceContextMode = InstanceContextMode.PerSession)]
	public class Service1 : IService1
	{
		private readonly IService1 Service1Impl = ServiceLocator.Instance.GetService<IService1>();
				public YongHuXXDTO GetYongHuXXByCID(String cid)
		{
			try
			{
				return Service1Impl.GetYongHuXXByCID(cid);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public Boolean AddYongHuXX(YongHuXXDTO dto)
		{
			try
			{
				return Service1Impl.AddYongHuXX(dto);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public String GetData(Int32 value)
		{
			try
			{
				return Service1Impl.GetData(value);
			}
			catch(Exception ex)
			{
				throw new FaultException<FaultData>(FaultData.CreateFromException(ex), FaultData.CreateFaultReason(ex));
			}
		}
		public void Dispose() { Service1Impl.Dispose(); }
	}
}